language: php
php:
    - '5.6'
    - '7.0'
    - hhvm
services:
    - mongodb
before_script:
    - if [ ! "$HHVM_VERSION" ]; then pecl install mongodb; fi
    - echo "extension=mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - composer self-update
    - composer install --prefer-source --no-interaction
script:
    - composer build-test
